### ISSUE TITLE
Worthless and RATTED with SEROXEN

### ISSUE THREAD

**Issue by f4getfull** [lunakittyyy/GorillaXS#4]
THIS IS RATTED WITH SEROXEN AND IS WORTHLESS AND YOU DONT NEED TO PAY FOR IT YOU CAN MAKE THIS SHIT FOR FREE

**Comment by lunakittyyy** [comment]
I didn't make XSOverlay. I can't make an application free just because I use its API. 
Please kindly go away and stop wasting my time

**Comment by lunakittyyy** [comment]
Also SeroXen has been discontinued for months I couldn't have ratted this mod with it if I wanted to :skull:
